site_name: Automated Flight Planning Software Documentation
site_description: Documentation for Automated Flight Planning Software for ground control.
theme:
  name: material
nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Features: features.md
  - Usage Instructions: usage-instructions.md
  - Configuration Options: configuration-options.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Support: support.md
